/* cmdline.h */

/* File autogenerated by gengetopt version 2.12.2  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE PACKAGE
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  char * import_format_arg;	/* Force the file format of the file(s) specified (default='AUTODETECT').  */
  int msg_parser_flag;	/* Output file parsing messages (default=off).  */
  int msg_debug_flag;	/* Output messages meant for debuging (default=off).  */
  int msg_warning_flag;	/* Output warning messages about abnormal conditions and unknown constructs (default=on).  */
  int msg_error_flag;	/* Output error messages (default=on).  */
  int msg_info_flag;	/* Output informational messages about the progress of the library (default=on).  */
  int msg_status_flag;	/* Output status messages (default=on).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int import_format_given ;	/* Whether import-format was given.  */
  int list_import_formats_given ;	/* Whether list-import-formats was given.  */
  int msg_parser_given ;	/* Whether msg_parser was given.  */
  int msg_debug_given ;	/* Whether msg_debug was given.  */
  int msg_warning_given ;	/* Whether msg_warning was given.  */
  int msg_error_given ;	/* Whether msg_error was given.  */
  int msg_info_given ;	/* Whether msg_info was given.  */
  int msg_status_given ;	/* Whether msg_status was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
